### ISSUE TITLE
Feature: Support of container elements

### ISSUE THREAD

**Issue by raswonders** [raswonders/bootstrap-grid-overlay#2]
# Task

Add support of container elements

## Description

Container is important element in layout, visualizing it together with rows might help understanding layout.

- [x] refactor change initGridOverlay to createRowOverlay
- [x] refactor positionGridOverlay to positionOverlayElement
- [x] detection of container elements
- [x] create map of container element and its overlay element
- [x] create createContainerOverlay
- [x] create styles for container element
- [x] refactor extend updateOverlays to include container elements

**Comment by raswonders** [comment]
Implemented
